[build-system]

requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]

name = "plug"
version = "0.0.1"
description = "Plug"
readme = "README.md"
dependencies = [
    "pyyaml==6.0.1",
	"pyzmq==25.0.2", 
  ]

[project.optional-dependencies]

listen = ['pynput']

[tool.setuptools.packages.find]

where = ["plug"]

[tool.setuptools.package-data]

umay = ["*.ini", "*.yaml"]
