[build-system]

requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]

name = "plug"
version = "0.0.1"
description = "Plug"
readme = "README.md"
dependencies = [
    "pyyaml==6.0.1",
	"pyzmq==25.0.2", 
  ]

[project.optional-dependencies]

qplug=[
	"gizmo==0.0.1",
	"pynput==1.7.6",
	"PyQt5==5.15.9",
	"PyQtWebEngine==5.15.6",
	]

[tools.setuptools.package-data]

"*"=["*"]

[tools.setuptools.packages.find]

where=["src"]
